name: demo_dash_app_env

channels:
	- conda-forge
	- anaconda
	- plotly
	- defaults

dependencies:
	- python>=3.6
	- brotli==1.0.9
	- click==8.0.4
	- dash==2.3.0
	- dash-bootstrap-components==1.0.3
	- dash-core-components==2.0.0
	- dash-extensions==0.0.71
	- dash-html-components==2.0.0
	- dash-table==5.0.0
	- editorconfig==0.12.3
	- et-xmlfile==1.1.0
	- flask==2.0.3
	- flask-caching==1.10.1
	- flask-compress==1.11
	- itsdangerous==2.1.1
	- jinja2==3.0.3
	- jsbeautifier==1.14.0
	- markupsafe==2.1.1
	- more-itertools==8.12.0
	- numpy==1.22.3
	- openpyxl==3.0.9
	- pandas==1.4.1
	- plotly==5.6.0
	- python-dateutil==2.8.2
	- pytz==2022.1
	- six==1.16.0
	- tenacity==8.0.1
	- werkzeug==2.0.3
	- xlsxwriter==3.0.3
