name: demo_dash_app

channels:
  - conda-forge
  - anaconda
  - plotly
  - defaults

dependencies:
  - python>=3.6
  - pip
  - openpyxl
  - xlsxwriter
  - numpy>=1.0
  - pandas>=1.0
  - plotly>=5.0
  - dash>=2.3
  - dash-bootstrap-components>=1.0
